//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterPol
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.InteropServices;

    public partial class Partner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Partner()
        {
            this.PartnerProduct = new HashSet<PartnerProduct>();
        }
    
        public int ID { get; set; }
        public int PartnerTypeID { get; set; }
        public string PartnerName { get; set; }
        public string DirectorName { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string LegalAddress { get; set; }
        public string TaxNumber { get; set; }
        public int Rating { get; set; }

        public string PartnerTypeName
        {
            get
            {
                return PartnerType.PartnerTypeName;
            }
        }

        public int Discount
        {
            get
            {
                int prodCount = 0;
                foreach(PartnerProduct partnerProduct in PartnerProduct)
                {
                    if (partnerProduct.PartnerID == ID)
                        prodCount += partnerProduct.ProductQuantity;
                }
                if (prodCount < 10000)
                    return 0;
                else
                {
                    if (prodCount >= 10000 && prodCount < 50000)
                        return 5;
                    else
                    {
                        if (prodCount >= 50000 && prodCount < 300000)
                            return 10;
                        else return 15;
                    }
                }
            }
        }
    
        public virtual PartnerType PartnerType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartnerProduct> PartnerProduct { get; set; }
    }
}
